n <- 24
#seed <- 682 # sample(seq(100,999),1)
#c(seed=seed)
set.seed(682)
gr1 <- c("Left","Right")
gr2 <- c("Low","Medium","High")
gr3 <- c("Station_1","Station_2")
gr1 <- sample(gr1,n,replace=TRUE) |> factor(levels=gr1,ordered=TRUE)
gr2 <- sample(gr2,n,replace=TRUE) |> factor(levels=gr2,ordered=TRUE)
gr3 <- sample(gr3,n,replace=TRUE) |> factor(levels=gr3,ordered=!TRUE)
# gr3 <- as.integer(gr3)
da <- data.frame(gr1=gr1,gr2=gr2,gr3=gr3)
str(da)
require(ggplot2)
p <- ggplot(da,aes(gr3,gr2,color=gr3))
# p <- ggplot(da,aes(gr1,gr2))
p <- p+scale_x_discrete(labels=element_blank(),position="top")
p <- p+scale_y_discrete(labels=element_blank(),position="right")
#p <- p+geom_jitter(aes(gr1,gr2,color=gr3),width = 0.3, height = 0.3)
#p <- p+geom_count(position=position_dodge(width=0))
p <- p+geom_jitter(position=position_jitterdodge(jitter.height=0.3,jitter.width=0.8,dodge.width=0))
#p <- p+geom_point(position=position_jitter(height=0.2))
# p <- p+geom_violin()
p <- p+facet_grid(gr2~gr1,scales="free",space="free",as.table=FALSE,switch="both")
# p <- p+geom_count(position=position_dodge(width=0.2))
p <- p+theme_minimal()
#p <- p+theme(strip.text.x=element_blank())
#p <- p+theme(strip.text.y=element_blank())
p
