---
pagetitle: Таймыр осень
title: Анализ данных с метеостанций Таймыра
subtitle: Оценка возможных погодных условий осенних работ 2024 г.
author:
 - name: Платонов Н. Г.
   affiliation: ИПЭЭ РАН
report: true
sevin: true
toc: true
toc_depth: 3
---

# Введение

Цель осенних работ на Таймыре -- оценка распределения белого медведя в безледовый период на побережье Таймыра и отловы белого медведя с использованием вертолётной техники с базированием в пос. Диксон (или на о. Диксон). Такие работы считаются метеочувствительными, поэтому проведен анализ метеорологических данных прошлых лет для периода планируемых работ в августе-сентябре как с метеостанции о. Диксон [@rp5-20674], так и с ближайших метеостанций.

# Данные и методы

Использованы данные с ресурса rp5.ru [@rp5]. Ближайшая метеостанция к месту базирования -- о. Диксон [@rp5-26074]. Запланированы маршруты, преимущественно, вдоль побережья как к востоку от точки базирования, в сторону метеостанции м. Стерлегова [@rp5-20476], так и к югу, в сторону метеостанции в Сопочной Карге [@rp5-]

